author: "@re1"
baseURL: https://re1.at
language: en
relativeURLs: true
theme: mojito
title: "@re1"
publishdir: public
params:
    description: Yet another draggy weblog
    subtitle: Software dev addicted to art
    github: re1
    twitter: re1coy
